source 'https://rubygems.org'
gem 'rails',                         '4.2.0'
gem 'mysql2'
gem 'sass-rails',                    '~> 5.0'
gem 'uglifier',                      '>= 1.3.0'
gem 'coffee-rails',                  '~> 4.1.0'
gem 'jquery-rails',                  '4.0.3'
gem 'jquery-ui-rails',               '5.0.3'
gem 'turbolinks'
gem 'jbuilder',                      '~> 2.0'
gem 'sdoc',                          '~> 0.4.0', group: :doc
gem 'bcrypt',                        '~> 3.1.7'
gem 'twitter-bootstrap-rails',       '3.2.0'
gem 'less-rails'
gem 'therubyracer',                  '0.12.1'
gem 'paperclip',                     '~> 4.2'
gem 'rmagick'
gem 'devise',                        '3.4.1'
gem 'carmen',                        '1.0.1'
gem 'nested_form'
gem 'rails4-autocomplete'
gem 'workflow'
gem 'kaminari'
gem 'ransack'
group :production do
  gem 'rails_12factor'
  gem 'pg'
end
group :development, :test do
  gem 'byebug'
  gem 'web-console',                 '~> 2.0'
  gem 'spring'
  gem 'better_errors',                              '~> 2.0.0'
end
